"use client";
function accountRisks(a:any){const r=[];if(a.employee?.employment_status==="departed"&&a.account_status!=="disabled")r.push("离职未停用");if(!a.employee&&!a.responsible_owner)r.push("无人认领");if(a.is_privileged)r.push("高权限");if(["unknown","locked"].includes(a.account_status))r.push("状态异常");return r}
export function GovernanceWorkspace({data,go}:{data:any;go:(x:string)=>void}){
 const accounts=data.accounts||[],employees=data.employees||[],departments=data.departments||[],devices=data.governance?.devices||[],connectors=data.governance?.connectors||[];
 const people=new Set(accounts.map((a:any)=>a.employee?.id||a.responsible_owner||"未认领")),owned=accounts.filter((a:any)=>a.employee||a.responsible_owner).length,assignedDevices=devices.filter((d:any)=>d.custodian||d.department).length,activeConnectors=connectors.filter((c:any)=>c.status!=="error").length;
 const indicators=[
  {name:"账号责任覆盖率",done:owned,all:accounts.length||1,detail:`${owned}/${accounts.length} 个账号已关联人员或责任人`,go:"账号台账"},
  {name:"员工账号关联率",done:employees.filter((e:any)=>accounts.some((a:any)=>a.employee?.id===e.id)).length,all:employees.length||1,detail:`${people.size} 人共关联 ${accounts.length} 个平台账号`,go:"账号台账"},
  {name:"设备责任覆盖率",done:assignedDevices,all:devices.length||1,detail:`${assignedDevices}/${devices.length} 台设备已明确部门或责任人`,go:"设备资产"},
  {name:"同步连接可用率",done:activeConnectors,all:connectors.length||1,detail:`${activeConnectors}/${connectors.length} 个连接器当前可用`,go:"同步中心"}
 ];
 return <div className="content governance"><section className="governance-hero"><div><span>内部管理数据概览</span><h2>企业账号与设备资产统一管理</h2><p>集中管理员工、部门、平台账号、设备资产及数据同步。</p></div><b>midPoint 连接正常</b></section><div className="governance-metrics"><button onClick={()=>go("员工管理")}><span>员工总数</span><b>{employees.length}</b><small>{departments.length} 个部门</small></button><button onClick={()=>go("账号台账")}><span>平台账号</span><b>{accounts.length}</b><small>关联 {people.size} 人</small></button><button onClick={()=>go("设备资产")}><span>设备资产</span><b>{devices.length}</b><small>{assignedDevices} 台已明确责任</small></button><button onClick={()=>go("同步中心")}><span>同步连接器</span><b>{connectors.length}</b><small>{activeConnectors} 个当前可用</small></button></div><section className="panel readiness"><div className="pt"><div><h3>台账完整度</h3><p>根据当前员工、账号、设备和同步数据自动统计，点击可查看明细。</p></div></div><div className="readiness-grid">{indicators.map(x=>{const pct=Math.min(100,Math.round(x.done/x.all*100));return <button key={x.name} onClick={()=>go(x.go)}><div><b>{x.name}</b><span>{pct}%</span></div><i><em style={{width:pct+"%"}}/></i><small>{x.detail}</small></button>})}</div></section><div className="governance-cols"><section className="panel action-list"><div className="pt"><div><h3>快捷入口</h3><p>直接进入常用管理功能</p></div></div><button onClick={()=>go("账号台账")}><i>1</i><div><b>查看人员平台账号</b><span>按人员汇总并展开查看各平台账号</span></div><strong>进入 →</strong></button><button onClick={()=>go("设备资产")}><i>2</i><div><b>维护设备资产台账</b><span>登记、导入、编辑、领用和归还设备</span></div><strong>进入 →</strong></button><button onClick={()=>go("同步中心")}><i>3</i><div><b>管理同步连接器</b><span>新增、同步或删除系统连接器</span></div><strong>进入 →</strong></button></section><section className="panel scope-card"><div className="pt"><div><h3>当前管理范围</h3><p>首页数据来源</p></div></div><ul><li><b>员工与部门</b><span>维护组织人员基础信息</span></li><li><b>平台账号</b><span>按人员汇总各系统登录账号</span></li><li><b>设备资产</b><span>管理设备台账和领用状态</span></li><li><b>同步连接</b><span>管理外部系统数据同步</span></li></ul></section></div></div>
}
export function LifecyclePage({data,go}:{data:any;go:(x:string)=>void}){const noAccount=data.employees.filter((e:any)=>e.employment_status==="active"&&!data.accounts.some((a:any)=>a.employee?.id===e.id)),departedOpen=data.accounts.filter((a:any)=>a.employee?.employment_status==="departed"&&a.account_status!=="disabled"),unowned=data.accounts.filter((a:any)=>!a.employee&&!a.responsible_owner);const groups=[{title:"入职待确认",tone:"blue",rows:noAccount.map((e:any)=>({name:e.name,detail:"在职员工尚未关联任何系统账号",action:"确认账号开通范围"}))},{title:"离职待回收",tone:"red",rows:departedOpen.map((a:any)=>({name:a.username,detail:`${a.employee?.name||"离职人员"} · ${a.system?.name||"未知系统"}`,action:"执行停用并记录结果"}))},{title:"账号待认领",tone:"amber",rows:unowned.map((a:any)=>({name:a.username,detail:a.system?.name||"未知系统",action:"补充关联人员或责任人"}))}];return <div className="content lifecycle"><div className="process-flow"><article><i>1</i><b>入职</b><span>身份建立与基线权限</span></article><em>→</em><article><i>2</i><b>转岗</b><span>原权限回收与新权限审批</span></article><em>→</em><article><i>3</i><b>离职</b><span>账号停用、会话撤销与数据交接</span></article><em>→</em><article><i>4</i><b>归档</b><span>执行记录与独立复核</span></article></div><div className="lifecycle-grid">{groups.map(g=><section className={`panel task-group ${g.tone}`} key={g.title}><header><h3>{g.title}</h3><b>{g.rows.length}</b></header>{g.rows.length?g.rows.slice(0,8).map((r:any,i:number)=><article key={i}><div><b>{r.name}</b><span>{r.detail}</span></div><small>{r.action}</small></article>):<p>当前无待办事项</p>}</section>)}</div><section className="evidence-rule"><b>流程关闭条件</b><span>完成执行人、执行时间、系统结果及复核人记录后，方可关闭任务。</span><button onClick={()=>go("审计留痕")}>查看操作记录</button></section></div>}
export function EvidencePage({data,go}:{data:any;go:(x:string)=>void}){const requirements=[{name:"业务触发来源",desc:"入职、转岗、离职、人工申请或定期复核"},{name:"审批记录",desc:"直属经理、应用负责人及安全或 IT 审批信息"},{name:"执行结果",desc:"目标账号 ID、执行时间及成功或失败回执"},{name:"操作凭证",desc:"系统回执、日志编号、截图或可验证链接"},{name:"独立复核",desc:"复核人、复核时间及最终处理结论"}];return <div className="content evidence"><section className="evidence-status"><div><span>核查记录</span><b>{data.reviews.length}</b></div><div><span>已纳管账号</span><b>{data.accounts.length}</b></div><div><span>核查覆盖率</span><b>{data.accounts.length?Math.round(data.reviews.length/data.accounts.length*100):0}%</b></div><p>平台统一记录账号操作、审批结果、处置凭证和复核信息，支持全过程审计追溯。</p></section><section className="panel evidence-checklist"><div className="pt"><div><h3>账号操作记录要求</h3><p>关键操作应保留完整的业务依据、执行结果及复核记录。</p></div></div>{requirements.map((x,i)=><article key={x.name}><i>{i+1}</i><div><b>{x.name}</b><span>{x.desc}</span></div><em>{i<2?"流程记录":i===2?"系统记录":"审计归档"}</em></article>)}</section><section className="securitynote"><b>记录管理</b><span>生命周期、风险整改和设备资产操作均关联操作人员、时间及凭证编号，可在审计留痕中统一查询。</span><button onClick={()=>go("风险整改")}>查看风险事项</button></section></div>}
export function PermissionPage({roleName}:{roleName:string}){const rows=[{role:"超级管理员",scope:"全平台",actions:"配置角色、管理用户、全部增删改、连接器和审计",limit:"仅限授权人员，建议启用 MFA"},{role:"IT账号管理员",scope:"日常运维",actions:"人员、部门、应用和账号维护；生命周期与同步",limit:"无超级管理员授予权限"},{role:"应用负责人",scope:"负责的应用",actions:"查看应用账号、审批申请、发起复核和确认整改",limit:"不含其他应用及平台配置"},{role:"审计人员",scope:"全局只读审计",actions:"查看台账、风险、审批、操作和凭证记录",limit:"无业务数据修改权限"},{role:"只读用户",scope:"授权范围",actions:"查看允许的应用和账号摘要",limit:"无敏感字段及操作权限"}];return <div className="content permission-page"><section className="current-role"><div><span>当前登录角色</span><h2>{roleName==="Administrator"?"超级管理员":roleName}</h2><p>系统同时在界面和服务端实施权限校验。</p></div><b>分级权限控制</b></section><section className="panel permission-matrix"><div className="pt"><div><h3>角色权限矩阵</h3><p>遵循最小权限、职责分离和审计可追溯原则。</p></div></div><div className="tw"><table><thead><tr><th>角色</th><th>数据范围</th><th>允许操作</th><th>权限边界</th></tr></thead><tbody>{rows.map(r=><tr className={r.role===(roleName==="Administrator"?"超级管理员":roleName)?"role-current":""} key={r.role}><td><b>{r.role}</b>{r.role===(roleName==="Administrator"?"超级管理员":roleName)&&<em>当前</em>}</td><td>{r.scope}</td><td>{r.actions}</td><td>{r.limit}</td></tr>)}</tbody></table></div></section><section className="securitynote"><b>权限说明</b><span>用户权限以 midPoint 角色分配结果为准，角色调整后需重新登录方可生效。</span></section></div>}
