import type { NextRequest } from "next/server";
export const dynamic = "force-dynamic";
type Ctx = { params: Promise<{ path?: string[] }> };
const base = (process.env.MIDPOINT_URL || "http://127.0.0.1:8080/midpoint").replace(/\/$/, "");
const PORTAL_SESSION_MS = 30 * 24 * 60 * 60 * 1000;
function val(x: any): string { if (x == null) return ""; if (["string","number"].includes(typeof x)) return String(x); return String(x.orig ?? x.norm ?? x["@value"] ?? x.name?.orig ?? ""); }
function firstVal(x:any):string{if(Array.isArray(x)){for(const item of x){const value=firstVal(item);if(value)return value}return""}return val(x)}
function list(x: any): any[] { const v=x?.object?.object ?? x?.object ?? x; return Array.isArray(v)?v:v?.oid?[v]:[]; }
async function mp(path:string,auth:string,init:RequestInit={}) { const r=await fetch(base+"/ws/rest"+path,{...init,headers:{Accept:"application/json","Content-Type":"application/json",Authorization:auth,...init.headers},cache:"no-store"}); const raw=await r.text(); let j:any=null; try{j=raw?JSON.parse(raw):null}catch{} if(!r.ok)throw Object.assign(new Error(val(j?.operationResult?.message)||val(j?.object?.message)||val(j?.message)||`midPoint HTTP ${r.status}`),{status:r.status}); return j; }
async function search(type:string,auth:string){return list(await mp(`/${type}/search?options=resolveNames`,auth,{method:"POST",body:JSON.stringify({query:""})}));}
function employee(x:any){const state=val(x.activation?.effectiveStatus||x.activation?.administrativeStatus).toLowerCase(),assignments=Array.isArray(x.assignment)?x.assignment:x.assignment?[x.assignment]:[],orgRef=assignments.map((a:any)=>a?.targetRef).find((r:any)=>/OrgType/i.test(val(r?.type)||val(r?.relation))),parentRef=Array.isArray(x.parentOrgRef)?x.parentOrgRef[0]:x.parentOrgRef,ref=orgRef||parentRef,depId=val(ref?.oid),depName=val(ref?.targetName)||firstVal(x.organizationalUnit)||firstVal(x.extension?.department);return{id:x.oid,employee_no:val(x.employeeNumber)||val(x.name),name:val(x.fullName)||[val(x.givenName),val(x.familyName)].filter(Boolean).join(" ")||val(x.name),email:val(x.emailAddress),employment_status:state==="disabled"||state==="archived"?"departed":"active",termination_date:val(x.activation?.validTo),status:state==="disabled"||state==="archived"?"inactive":"active",department:depId||depName?{id:depId||depName,name:depName||depId}:null};}
function department(x:any){const description=val(x.description),savedManager=description.match(/负责人：([^；]+)/)?.[1]?.trim()||"";return{id:x.oid,name:val(x.displayName)||val(x.name),manager:val(x.managerRef?.targetName)||savedManager,status:val(x.activation?.effectiveStatus).toLowerCase()==="disabled"?"inactive":"active"};}
function metadata(x:any){const raw=val(x.description);if(!raw.startsWith("FANTUAN_META:"))return{};try{return JSON.parse(raw.slice(13))}catch{return{}};}
function system(x:any){const m=metadata(x);return{id:x.oid,name:val(x.displayName)||val(x.name),system_type:m.system_type||"internal",url:m.url||"",owner:m.owner||val(x.ownerRef?.targetName),it_owner:m.it_owner||"",risk_level:m.risk_level||"medium",review_cycle_days:Number(m.review_cycle_days)||90,status:val(x.activation?.effectiveStatus).toLowerCase()==="disabled"?"inactive":"active"};}
function account(x:any){const enabled=val(x.activation?.effectiveStatus||x.activation?.administrativeStatus).toLowerCase()!=="disabled",sys=val(x.resourceRef?.targetName)||val(x.resourceRef?.oid),owner=val(x.correlation?.ownerRef?.targetName)||val(x.linkRef?.targetName);return{id:x.oid,username:val(x.primaryIdentifierValue)||val(x.name),account_status:enabled?"active":"disabled",role_name:val(x.intent)||val(x.kind),is_privileged:false,last_login_at:val(x.extension?.lastLoginAt),responsible_owner:owner,status:enabled?"active":"inactive",employee:owner?{id:val(x.correlation?.ownerRef?.oid),name:owner}:null,system:sys?{id:val(x.resourceRef?.oid),name:sys}:null};}
function portalRole(x:any){if(val(x.name)==="administrator")return"Administrator";const refs=[...(Array.isArray(x.roleMembershipRef)?x.roleMembershipRef:x.roleMembershipRef?[x.roleMembershipRef]:[]),...(Array.isArray(x.assignment)?x.assignment.map((a:any)=>a.targetRef):x.assignment?.targetRef?[x.assignment.targetRef]:[])];for(const ref of refs){const byOid=portalRoles.find(role=>role.id===val(ref?.oid));if(byOid)return byOid.name;}const names=refs.map((r:any)=>val(r?.targetName)||val(r?.name)).filter(Boolean);const rules=[{keys:["superuser","超级管理员","administrator"],role:"Administrator"},{keys:["it账号管理员","账号管理员","identity administrator","idm administrator"],role:"IT账号管理员"},{keys:["应用负责人","application owner","app owner"],role:"应用负责人"},{keys:["审计人员","auditor","audit"],role:"审计人员"},{keys:["只读用户","read only","readonly","viewer"],role:"只读用户"}];const lower=names.map((n:string)=>n.toLowerCase());for(const rule of rules)if(lower.some((name:string)=>rule.keys.some(key=>name.includes(key))))return rule.role;return"只读用户";}
function loginName(auth:string){try{return Buffer.from(auth.replace(/^Basic\s+/i,""),"base64").toString("utf8").split(":",1)[0].trim().toLowerCase()}catch{return"";}}
const ok=(data:any)=>Response.json({data});
const portalRoles=[
 {id:"00000000-0000-0000-0000-000000000004",name:"Administrator",description:"超级管理员"},
 {id:"f1000000-0000-4000-8000-000000000001",name:"IT账号管理员",description:"负责日常身份与账号治理"},
 {id:"f1000000-0000-4000-8000-000000000002",name:"应用负责人",description:"负责指定应用的账号审批与复核"},
 {id:"f1000000-0000-4000-8000-000000000003",name:"审计人员",description:"只读查看审计、风险与证据"},
 {id:"f1000000-0000-4000-8000-000000000004",name:"只读用户",description:"只读查看授权范围内的数据"},
];
const REST_ALL="http://midpoint.evolveum.com/xml/ns/public/security/authorization-rest-3#all",MODEL="http://midpoint.evolveum.com/xml/ns/public/security/authorization-model-3#";
function roleAuthorizations(name:string){const objectTypes=["UserType","OrgType","ServiceType","ShadowType","RoleType"].map(type=>({type})),read={name:"portal-read",action:[MODEL+"read"],object:objectTypes},rest={name:"portal-rest",action:[REST_ALL]};if(name==="IT账号管理员")return[rest,read,{name:"portal-write",action:[MODEL+"add",MODEL+"modify",MODEL+"delete"],object:objectTypes}];return[rest,read];}
async function ensurePortalRole(roleId:string,auth:string){const role=portalRoles.find(r=>r.id===roleId);if(!role||role.name==="Administrator")return;const internalNames:Record<string,string>={"IT账号管理员":"portal-it-account-admin","应用负责人":"portal-application-owner","审计人员":"portal-auditor","只读用户":"portal-read-only"};const definition={oid:role.id,name:internalNames[role.name]||safeName(role.name,role.id),displayName:role.name,description:role.description,authorization:roleAuthorizations(role.name)};try{await mp(`/roles/${role.id}`,auth);return}catch(e:any){if(e?.status!==404)throw e;}await mp("/roles",auth,{method:"POST",body:JSON.stringify({role:definition})});}
const roleInfo=(name:string)=>portalRoles.find(r=>r.name===name)||portalRoles[4];
async function currentUser(auth:string){const raw=await mp("/self?options=raw",auth);return raw?.user??raw;}
async function updatePortalUser(oid:string,data:any,auth:string){const self=await currentUser(auth),targetRaw=await mp(`/users/${oid}?options=raw`,auth),target=targetRaw?.user??targetRaw,targetName=val(target.name).toLowerCase();if(self.oid===oid&&data.status&&data.status!=="active")throw Object.assign(new Error("不能停用当前登录账号"),{status:409});if(targetName==="administrator"&&((data.status&&data.status!=="active")||(data.role&&data.role!==portalRoles[0].id)))throw Object.assign(new Error("内置 administrator 必须保持启用和超级管理员角色"),{status:409});const items:any[]=[];if(data.status)items.push({modificationType:"replace",path:"activation/administrativeStatus",value:data.status==="active"?"enabled":"disabled"});if(data.role){await ensurePortalRole(String(data.role),auth);const assignments=Array.isArray(target.assignment)?target.assignment:target.assignment?[target.assignment]:[],portalIds=new Set(portalRoles.map(r=>r.id)),kept=assignments.filter((x:any)=>!portalIds.has(val(x?.targetRef?.oid))),next=[...kept,{targetRef:{oid:String(data.role),type:"RoleType"}}];items.push({modificationType:"replace",path:"assignment",value:next});}if(items.length)await mp(`/users/${oid}`,auth,{method:"PATCH",body:JSON.stringify({objectModification:{itemDelta:items}})});return{};}
async function deletePortalUser(oid:string,auth:string){const self=await currentUser(auth),targetRaw=await mp(`/users/${oid}?options=raw`,auth),target=targetRaw?.user??targetRaw;if(self.oid===oid)throw Object.assign(new Error("不能删除当前登录账号"),{status:409});if(val(target.name).toLowerCase()==="administrator")throw Object.assign(new Error("不能删除内置超级管理员"),{status:409});await mp(`/users/${oid}`,auth,{method:"DELETE"});}
const safeName=(x:any,fallback:string)=>String(x||fallback).trim().replace(/\s+/g,"-");
const portalLogin=(email:any)=>String(email||"").trim().toLowerCase().replace(/@/g,"-at-").replace(/[^a-z0-9._-]+/g,"-").replace(/^-+|-+$/g,"");
const active=(status:any)=>status==="inactive"||status==="departed"?"disabled":"enabled";
async function create(type:string,data:any,auth:string){let body:any;
 if(type==="employees")body={user:{name:safeName(data.employee_no||data.email,`user-${Date.now()}`),fullName:data.name,emailAddress:data.email||undefined,employeeNumber:data.employee_no||undefined,organizationalUnit:data.department?String(data.department):undefined,activation:{administrativeStatus:active(data.employment_status||data.status)}}};
 else if(type==="departments")body={org:{name:safeName(data.name,`org-${Date.now()}`),displayName:data.name,description:data.manager?`负责人：${data.manager}`:"",activation:{administrativeStatus:active(data.status)}}};
 else if(type==="systems")body={service:{name:safeName(data.name,`service-${Date.now()}`),displayName:data.name,description:"FANTUAN_META:"+JSON.stringify({system_type:data.system_type||"internal",url:data.url||"",owner:data.owner||"",it_owner:data.it_owner||"",risk_level:data.risk_level||"medium",review_cycle_days:Number(data.review_cycle_days)||90}),activation:{administrativeStatus:active(data.status)}}};
 else throw Object.assign(new Error("此对象暂不支持在门户中新建"),{status:501});
 await mp(`/${type==="employees"?"users":type==="departments"?"orgs":"services"}`,auth,{method:"POST",body:JSON.stringify(body)});return{};}
async function modify(type:string,oid:string,data:any,auth:string){const endpoint=type==="employees"?"users":type==="departments"?"orgs":type==="systems"?"services":"";if(!endpoint)throw Object.assign(new Error("此对象暂不支持在门户中修改"),{status:501});const items:any[]=[];const put=(path:string,v:any)=>{if(v!==undefined)items.push({modificationType:"replace",path,value:v});};
 if(type==="employees"){put("fullName",data.name);put("emailAddress",data.email);put("employeeNumber",data.employee_no);put("organizationalUnit",data.department?String(data.department):undefined);put("activation/administrativeStatus",active(data.employment_status||data.status));if(data.termination_date)put("activation/validTo",data.termination_date);}
 if(type==="departments"){put("displayName",data.name);put("description",data.manager?`负责人：${data.manager}`:"");put("activation/administrativeStatus",active(data.status));}
 if(type==="systems"){put("displayName",data.name);put("description","FANTUAN_META:"+JSON.stringify({system_type:data.system_type||"internal",url:data.url||"",owner:data.owner||"",it_owner:data.it_owner||"",risk_level:data.risk_level||"medium",review_cycle_days:Number(data.review_cycle_days)||90}));put("activation/administrativeStatus",active(data.status));}
 await mp(`/${endpoint}/${oid}`,auth,{method:"PATCH",body:JSON.stringify({objectModification:{itemDelta:items}})});return{};}
async function handle(req:NextRequest,ctx:Ctx){const{path=[]}=await ctx.params;try{
 if(path[0]==="auth"&&path[1]==="login"&&req.method==="POST"){const b=await req.json(),token=Buffer.from(`${b.email}:${b.password}`,"utf8").toString("base64");await mp("/self?options=raw",`Basic ${token}`);return ok({access_token:token,refresh_token:token,expires:PORTAL_SESSION_MS});}
 if(path[0]==="auth"&&path[1]==="refresh"&&req.method==="POST"){const b=await req.json(),token=String(b.refresh_token||"");await mp("/self?options=raw",`Basic ${token}`);return ok({access_token:token,refresh_token:token,expires:PORTAL_SESSION_MS});}
 const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Basic "))return Response.json({errors:[{message:"请先登录 midPoint"}]},{status:401});
 const self=await currentUser(auth),callerRole=loginName(auth)==="administrator"?"Administrator":portalRole(self),writeAllowed=callerRole==="Administrator"||callerRole==="IT账号管理员";
 if(path[0]==="users"&&path[1]==="me"){const raw=await mp("/self?options=resolveNames",auth),self=raw?.user??raw,roleName=loginName(auth)==="administrator"?"Administrator":portalRole(self);return ok({id:self.oid||val(self.name)||loginName(auth),email:val(self.emailAddress)||val(self.name)||loginName(auth),first_name:val(self.givenName),last_name:val(self.familyName)||val(self.fullName),status:"active",last_access:"",role:{id:`midpoint-${roleName}`,name:roleName}});}
 if(path[0]==="users"&&req.method==="GET"){if(callerRole!=="Administrator")throw Object.assign(new Error("只有超级管理员可以查看平台用户"),{status:403});return ok((await search("users",auth)).map(x=>{const roleName=portalRole(x),r=roleInfo(roleName);return{...employee(x),email:val(x.emailAddress)||val(x.name),first_name:val(x.givenName),last_name:val(x.familyName)||val(x.fullName),role:{id:r.id,name:r.name}};}));}
 if(path[0]==="roles"&&req.method==="GET"){if(callerRole!=="Administrator")throw Object.assign(new Error("只有超级管理员可以查看角色"),{status:403});const actual=(await search("roles",auth)).map(x=>({id:x.oid,name:val(x.displayName)||val(x.name),description:val(x.description)}));return ok(portalRoles.map(r=>actual.find(x=>x.id===r.id)||r));}
 if(path[0]==="users"&&req.method==="POST"){if(callerRole!=="Administrator")throw Object.assign(new Error("只有超级管理员可以创建平台用户"),{status:403});const data=await req.json(),email=String(data.email||"").trim().toLowerCase();if(!email||!data.password)throw Object.assign(new Error("登录邮箱和初始密码不能为空"),{status:400});const roleId=String(data.role||portalRoles[4].id),login=portalLogin(email)||`user-${Date.now()}`,existing=await search("users",auth);if(existing.some(x=>val(x.name).toLowerCase()===login||val(x.emailAddress).toLowerCase()===email))throw Object.assign(new Error("该登录邮箱已存在，请直接使用已有账号或更换邮箱"),{status:409});await ensurePortalRole(roleId,auth);const body={user:{name:login,givenName:data.first_name,familyName:data.last_name,fullName:[data.first_name,data.last_name].filter(Boolean).join(" "),emailAddress:email,credentials:{password:{value:{clearValue:data.password}}},activation:{administrativeStatus:data.status==="active"?"enabled":"disabled"},assignment:{targetRef:{oid:roleId,type:"RoleType"}}}};try{await mp("/users",auth,{method:"POST",body:JSON.stringify(body)})}catch(e:any){if(e?.status===409)throw Object.assign(new Error("该账号已存在或与现有账号冲突，请更换登录邮箱"),{status:409});throw e}return ok({login});}
 if(path[0]==="users"&&path[1]&&req.method==="PATCH"){if(callerRole!=="Administrator")throw Object.assign(new Error("只有超级管理员可以调整平台用户"),{status:403});return ok(await updatePortalUser(path[1],await req.json(),auth));}
 if(path[0]==="users"&&path[1]&&req.method==="DELETE"){if(callerRole!=="Administrator")throw Object.assign(new Error("只有超级管理员可以删除平台用户"),{status:403});await deletePortalUser(path[1],auth);return new Response(null,{status:204});}
 if(path[0]==="items"&&req.method==="GET"){const ownerKeys=[loginName(auth),val(self.emailAddress).toLowerCase(),val(self.fullName).toLowerCase()].filter(Boolean);if(path[1]==="employees"){if(!writeAllowed&&callerRole!=="审计人员")throw Object.assign(new Error("当前角色不能查看员工目录"),{status:403});return ok((await search("users",auth)).map(employee));}if(path[1]==="departments"){if(!writeAllowed&&callerRole!=="审计人员")throw Object.assign(new Error("当前角色不能查看部门目录"),{status:403});return ok((await search("orgs",auth)).map(department));}if(path[1]==="systems"){let rows=(await search("services",auth)).map(system);if(callerRole==="应用负责人")rows=rows.filter((x:any)=>ownerKeys.some(k=>`${x.owner} ${x.it_owner}`.toLowerCase().includes(k)));return ok(rows);}if(path[1]==="accounts"){let rows=(await search("shadows",auth)).filter(x=>val(x.kind||"account")==="account").map(account);if(callerRole==="应用负责人"){const allowed=new Set((await search("services",auth)).map(system).filter((x:any)=>ownerKeys.some(k=>`${x.owner} ${x.it_owner}`.toLowerCase().includes(k))).map((x:any)=>x.id));rows=rows.filter((x:any)=>allowed.has(x.system?.id));}return ok(rows);}if(path[1]==="account_reviews"||path[1]==="licenses")return ok([]);}
 if(path[0]==="items"&&req.method==="POST"){if(!writeAllowed)throw Object.assign(new Error("当前角色没有写权限"),{status:403});return ok(await create(path[1],await req.json(),auth));}
 if(path[0]==="items"&&req.method==="PATCH"&&path[2]){if(!writeAllowed)throw Object.assign(new Error("当前角色没有写权限"),{status:403});return ok(await modify(path[1],path[2],await req.json(),auth));}
 if(path[0]==="items"&&req.method==="DELETE"&&path[2]){if(callerRole!=="Administrator")throw Object.assign(new Error("只有超级管理员可以永久删除对象"),{status:403});const endpoint=path[1]==="employees"?"users":path[1]==="departments"?"orgs":path[1]==="systems"?"services":"";if(!endpoint)throw Object.assign(new Error("此对象暂不支持在门户中删除"),{status:501});await mp(`/${endpoint}/${path[2]}`,auth,{method:"DELETE"});return new Response(null,{status:204});}
 return Response.json({errors:[{message:"该写操作尚未接入 midPoint；第一阶段已支持登录和核心数据读取。"}]},{status:501});
}catch(e:any){const status=Number(e?.status)||500;return Response.json({errors:[{message:status===401?"midPoint 用户名或密码不正确":e?.message||"midPoint 服务调用失败"}]},{status});}}
export const GET=handle;export const POST=handle;export const PATCH=handle;export const PUT=handle;export const DELETE=handle;export const OPTIONS=handle;
